const QuoteComponent = () => {
  return (
    <div className="hidden h-full w-[50vw] flex-col justify-end bg-zinc-900 p-16 md:flex">
      <div className="text-lg text-white">
        <p className="flex flex-col gap-5">
          <q className="text-lg" cite="https://chat.openai.com/">
            {
              "Why the medical app? Staying a step ahead of AI. They can't handle patients self-diagnosing with just a sneeze and a WebMD search!"
            }
          </q>
          <span className="text-sm">- generated by ChatGPT</span>
        </p>
      </div>
    </div>
  );
};

export default QuoteComponent;
